version: '3.1'

services:
  db:
    container_name: mysql8
    image: mysql:8.0
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: company
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    
    ports:
      - '3306:3306'